2024-12-22 19:24:54,227 - INFO - Successfully registered with ID: 1fafdd44-4aaf-4fd7-a3cb-9d80292ea919
2024-12-22 19:29:00,754 - INFO - Successfully registered with ID: 581df175-2445-4e36-9e49-627990e2bea6
2024-12-22 19:31:30,772 - ERROR - Heartbeat failed: HTTPConnectionPool(host='localhost', port=5000): Max retries exceeded with url: /heartbeat/581df175-2445-4e36-9e49-627990e2bea6 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fcdb55f8aa0>: Failed to establish a new connection: [Errno 111] Connection refused'))
2024-12-22 19:31:45,065 - INFO - Successfully registered with ID: 2cf79119-f01a-40e5-8b28-8188b30f9693
2024-12-22 19:32:15,081 - INFO - Executed command 9b711aaa-7594-41ec-bced-5ba93a207415: dir
2024-12-22 19:43:15,151 - ERROR - Heartbeat failed: HTTPConnectionPool(host='localhost', port=5000): Max retries exceeded with url: /heartbeat/2cf79119-f01a-40e5-8b28-8188b30f9693 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f2059602870>: Failed to establish a new connection: [Errno 111] Connection refused'))
2024-12-22 19:43:45,153 - ERROR - Heartbeat failed: HTTPConnectionPool(host='localhost', port=5000): Max retries exceeded with url: /heartbeat/2cf79119-f01a-40e5-8b28-8188b30f9693 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f2059400e30>: Failed to establish a new connection: [Errno 111] Connection refused'))
2024-12-22 19:44:15,154 - ERROR - Heartbeat failed: HTTPConnectionPool(host='localhost', port=5000): Max retries exceeded with url: /heartbeat/2cf79119-f01a-40e5-8b28-8188b30f9693 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f20597101d0>: Failed to establish a new connection: [Errno 111] Connection refused'))
2024-12-22 19:44:45,156 - ERROR - Heartbeat failed: HTTPConnectionPool(host='localhost', port=5000): Max retries exceeded with url: /heartbeat/2cf79119-f01a-40e5-8b28-8188b30f9693 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f2059401670>: Failed to establish a new connection: [Errno 111] Connection refused'))
2024-12-22 19:45:15,158 - ERROR - Heartbeat failed: HTTPConnectionPool(host='localhost', port=5000): Max retries exceeded with url: /heartbeat/2cf79119-f01a-40e5-8b28-8188b30f9693 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f2059401fa0>: Failed to establish a new connection: [Errno 111] Connection refused'))
2024-12-22 19:45:45,159 - ERROR - Heartbeat failed: HTTPConnectionPool(host='localhost', port=5000): Max retries exceeded with url: /heartbeat/2cf79119-f01a-40e5-8b28-8188b30f9693 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f20594028d0>: Failed to establish a new connection: [Errno 111] Connection refused'))
2024-12-22 19:46:15,161 - ERROR - Heartbeat failed: HTTPConnectionPool(host='localhost', port=5000): Max retries exceeded with url: /heartbeat/2cf79119-f01a-40e5-8b28-8188b30f9693 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f2059403200>: Failed to establish a new connection: [Errno 111] Connection refused'))
2024-12-22 19:46:45,162 - ERROR - Heartbeat failed: HTTPConnectionPool(host='localhost', port=5000): Max retries exceeded with url: /heartbeat/2cf79119-f01a-40e5-8b28-8188b30f9693 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f2059839100>: Failed to establish a new connection: [Errno 111] Connection refused'))
